name: Build

on:
  push:
    branches:
      - master
      - android-10
  pull_request:
    branches:
      - master
      - android-10
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
          distribution: 'temurin'  # Options: temurin, zulu, adopt, etc.
          java-version: '17'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Store generated APK file
      uses: actions/upload-artifact@v4
      with:
        name: termux-app
        path: ./app/build/outputs/apk/debug
